---
- name: Install frontend Smt-finder project dependencies
  shell: cd /vagrant/frontend && npm cache clean && npm install
  become: true
  become_user: vagrant

- name: Copy across new virtual host for frontend smt-finder
  template:
    src=nginx/frontend.conf.j2
    dest=/etc/nginx/sites-available/frontend.conf
  notify:
    - restart nginx

- name: Enable new vagrant virtual host for frontend smt-finder
  file:
    src=/etc/nginx/sites-available/frontend.conf
    dest=/etc/nginx/sites-enabled/frontend.conf
    state=link
  notify:
    - restart php-fpm
    - restart nginx
