---
- name: Install PostgreSQL
  apt: name={{item}} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

- name: Install setfacl support for resolving becoming user issue
  apt: pkg=acl

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Create PostgreSQL database
  become: yes
  become_user: postgres
  postgresql_db: name={{dbname}}

- name: Create user who has access to created database
  become: yes
  become_user: postgres
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: Reset unnecessary privilege for created user
  become: yes
  become_user: postgres
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
