---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    document_root: /vagrant
    www_user: vagrant
    www_group: vagrant
    dbname: smt-finder
    dbuser: smt-finder
    dbpassword: kcIxks92kI
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php-fpm
      service: name=php5-fpm state=restarted
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  tasks:
    - include: tasks/base.yml
    - include: tasks/nginx.yml
    - include: tasks/postgresql.yml
    - include: tasks/php.yml
    - include: tasks/php-devtools.yml
    - include: tasks/php-fpm.yml
    - include: tasks/npm.yml
    - include: tasks/backend.yml
    - include: tasks/frontend.yml
